### ISSUE TITLE
Changing settings in Beheer don't always work. 

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_tudelft#11]
When changing element settings in different sections of 'Beheer' (e.g. displays, user interfaces etc). they don't seem to save. 
For example:
I drag and drop a new element from left to right.
I click the i to change the settings of the element.
I change the label and restrict the relationship types.
I click the i on the bottom of the pop-up to close the pop-up.
I save the record.
Usually the changes are not saved from the first try and I have to try again. This should work from the first save of course. Please check and fix. 
![image](https://user-images.githubusercontent.com/3798589/40244967-9114fd26-5ac4-11e8-85c1-a8ec7ac19329.png)

**Comment by aruijmen** [comment]
Apparently CA expects you to work in 2 faces:
- first you add the field to the right column and you save this
- next you do all the editing stuff when clicking on the i  of the field and you save again.
This is the only way to avoid frustration in this department.
