### ISSUE TITLE
ca_collections display template - hierarchie collecties weergeven

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_tudelft#12]
Graag hierarchie weergeven voor collecties 

![image](https://user-images.githubusercontent.com/3798589/40245541-5578c200-5ac6-11e8-87b6-4c5600748a53.png)

**Comment by aruijmen** [comment]
Voor de collecties is het niet voorzien dat bij Nieuw -> Collecties of bij Vind -> Collecties -> Zoek een hierarchie viewer verschijnt (zoals bij places en storage_locations.
In de user interface is wel mogelijk om de Locatie in hierarchie te tonen.

Graag iets meer informatie

**Comment by roxannewyns** [comment]
Ik bedoel in de weergave van de zoekresultaten de hierarchie van de collectie weergeven in het metadata overzicht. Het heeft dus niets met het nieuw of vind menu te maken, maar met display templates/weergaves van zoekresultaten. 

Misschien heb je dat ondertussen in de voorbeeldweergaves al in orde gebracht.

**Comment by aruijmen** [comment]
De collectie weergave van zoek-resultaten ziet er nu (voorlopig) als volgt uit:

![image](https://user-images.githubusercontent.com/3263690/40478049-4be6c292-5f48-11e8-9ca8-a3b2a59bb318.png)
