### ISSUE TITLE
ca_storage_locations - hierarchie weergeven

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_tudelft#13]
Ook hier heirarchie weergeven van standsplaats in display template.

**Comment by aruijmen** [comment]
Vraagje:
over welke display template gaat het dan?
Bij Vind -> Opslagplaatsen -> Zoek verschijnt nu reeds het hierarchie venster?
Idem bij Nieuw -> Opslagplaats

Waar is de hierarchie viewer nog nodig?

**Comment by roxannewyns** [comment]
Ik bedoel in de weergave van de zoekresultaten de hierarchie van de collectie weergeven in het metadata overzicht. Het heeft dus niets met het nieuw of vind menu te maken, maar met display templates/weergaves van zoekresultaten.

**Comment by aruijmen** [comment]
Hopelijk is dit wat je bedoelt:

![image](https://user-images.githubusercontent.com/3263690/40478638-e980dfdc-5f49-11e8-91f2-955caa7ea770.png)
