### ISSUE TITLE
ca_object_representations

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_tudelft#2]
Momenteel staan object_representatons enkel in het Nieuw menu (Media). Dit moet ook in Vind menu toegevoegd worden zodat ze op reeds bestaande object representations kunnen zoeken. Dit is normaal een setting in de app.conf, maar mogelijk moet het nog extra toegevoegd worden in de navigation.conf.

Vanuit het ca_objects record willen ze ook kunnen linken aan reeds bestaande object_representations. Nu voorziet de browse functie enkel de mogelijkheid om nieuwe representation toe te voegen. 

Bij ca_aezel heb je dat ooit toegevoegd. Kan jij hetzelfde doen voor ca_delft. Graag ook even laten weten waar je dit aanpast, dan weet ik het ook.
![image](https://user-images.githubusercontent.com/3798589/40237582-2ab591a2-5ab1-11e8-80b4-45e13d508157.png)

**Comment by aruijmen** [comment]
Volgende wijzigingen aangebracht:
app.conf:ca_object_representations_breakout_find_by_type_in_submenu = 0
app.conf:ca_object_representations_breakout_find_by_type_in_menu = 0
app.conf:ca_objects_allow_relationships_to_existing_representations = 1
Gelieve nog even te controleren of het nu in orde is?

**Comment by roxannewyns** [comment]
Ok zo.
