### ISSUE TITLE
app.conf changes

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_tudelft#3]
@naeemmuhammad 
cc @aruijmen 

Please set all the following values in the app.conf file from 0 to 1 for ca_tudelft (in the test version as well).

# -------------------------------------------------------
# Restrict editing of codes for list and metadata elements
# ------------------------------------------------------
# Allowing free editing and code and data type settings can result in invalid configuration.
# The ability to edit these values once set can be restricted here.
#
ca_lists_dont_allow_editing_of_codes_when_in_use = 0
ca_list_items_dont_allow_editing_of_codes_when_in_use = 0
ca_metadata_elements_dont_allow_editing_of_codes_when_in_use = 0
ca_metadata_elements_dont_allow_editing_of_data_types_when_in_use = 0

**Comment by aruijmen** [comment]
Changes were made on Github heron-configuration
Online in current deployment
(not yet in test-instance) - waiting for surfnet connection is oke
