### ISSUE TITLE
tokenize / don't tokenize

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_tudelft#5]
Ik vermoed dat leestekents etc. weer genegeerd worden in ca_tudelft. Als je nu op A.E. Korvezee zoekt krijg je 0 resultaten. Als je op A E Korvezee zoekt 2. 

De setting moet zo staan dat hetgene is ingevoerd ook daadwerkelijk gevonden wordt. Dus A.E. Korvezee moet resultaten geven. Dit moet zo zijn voor alle velden, ook voor idno, relaties etc. 

Aanpassing ook doorvoeren in test. Of binnenkort een kopie van productie nemen eens dat deze OK staat als dat eenvoudiger is.

**Comment by aruijmen** [comment]
Roxanne,

Kan jij nog even een snelle test doen, om te kijken of het zoeken nu werkt zoals het hoort?

Bedankt

**Comment by roxannewyns** [comment]
Lijkt mij OK.
