### ISSUE TITLE
automatische doornummering erfgoed

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_tudelft#8]
partner wil graag dat nummering automatisch doorloopt. Na een eerte test lijkt het da de nummering enkel rekening houdt met het jaartal en dat je geen aparte nummering kan hebben per jaartal en lijst. 

Bij het plaatsen van de nummering op SERIAL krijg je 
2018.0001.EWI
2018.0002.EWI
2018.0003.SRC

Ze willen echter liever
2018.0001.EWI
2018.0002.EWI
2018.0001.SRC
2018.0002.SRC

Dat is ook hoe de oude nummering was en hoe het geïmporteerd werd. Te onderzoeken of hier oplossingen voor zijn. 

![image](https://user-images.githubusercontent.com/3798589/40242984-6b9e8ab2-5abf-11e8-85af-2c681716aec6.png)

**Comment by aruijmen** [comment]
Dit werkt inderdaad zo niet.
De enige oplossing die ik zie is: de volgorde van de onderdelen die nu year.volgnr.list is om te wisselen tot 
- ofwel year.list.volgnr 
- ofwel list.year.volgnr
en dan kunnen we wel met multipart_id_numbering onder de voeten uit.
Om automatisch een volgend nummer toe te kennen is het blijkbaar noodzakelijk dat het serial-deel helemaal achteraan staat (er wordt hierbij gesteund op de waardes van de idno_sort)

Concreet houdt dit in:
- huidige idno's vervangen (kan vrij eenvoudig met een sql update commando)
- sort-values opnieuw bepalen
- databank herindexeren
Best uit te voeren op een dood moment of in het weekend.
Maar tudelft moet uiteraard akkoord zijn.

**Comment by aruijmen** [comment]
De partener heeft laten weten dat zij niet te vinden zijn om de volgorde van de onderdelen van de idno om te draaien.  Maar zij gaan het nog verder intern bespreken.
Voorlopig even wachten.

**Comment by aruijmen** [comment]
Na interne bespreking heeft de partner laten weten dat ze hun nummering wensen aan te houden.
Om toch SNEL te weten wat het laatst gebruikte nummer in een jaar en groep is, werd een query aan de statistics van de objecten toegevoegd.
